apiVersion: skaffold/v1
kind: Config
metadata:
  name: requests
deploy:
  kubectl:
    manifests:
      - k8s/requests.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: discoenv/requests
  local: {}
